<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net9.0-windows;net462</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenTK.GLControl\OpenTK.GLControl.csproj" />
  </ItemGroup>

</Project>